[package]
name = "simulation"
version = "0.1.0"
edition = "2021"

[lib]
name = "simulation"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19", features = ["extension-module"] }
graph-simulation = { path = "lib/graph-simulation" }
